"""Prepare category relationship

Revision ID: 21d8cac78863
Revises: 8a043fc2f034
Create Date: 2021-02-06 16:27:14.706146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21d8cac78863"
down_revision = "8a043fc2f034"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("category_name", sa.String(), nullable=True))
        batch_op.drop_column("category")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("category_name")
        batch_op.drop_column("category_id")

    # ### end Alembic commands ###
