"""Add user name and id

Revision ID: dbc003708edb
Revises: aa8399c45583
Create Date: 2021-02-19 11:27:49.579060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dbc003708edb"
down_revision = "aa8399c45583"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("user_name", sa.String(), nullable=True))
        batch_op.drop_column("user")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("user_name")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
