"""Add names to users

Revision ID: ef61c2dec2ad
Revises: 3bd3d43e9ffc
Create Date: 2021-02-06 11:59:07.241857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef61c2dec2ad"
down_revision = "3bd3d43e9ffc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_data", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_data", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###
